version: '3'

tasks:
  clean:
    desc: clean all
    deps: 
      - task: clean:plugins
      - task: clean:state

  clean:plugins:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf $HOME/.local/share/nvim

  clean:state:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf $HOME/.local/state/nvim

  clean:swap:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf ./tmp/swap
      - mkdir ./tmp/swap

  clean:undo:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf ./tmp/undo
      - mkdir ./tmp/undo
