version: "3"

env:
  NVIM_APPNAME: nvim

tasks:
  clean:
    desc: clean all
    cmds:
      - task: clean:plugins
      - task: clean:state

  clean:plugins:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf $HOME/.local/share/$NVIM_APPNAME
      - mkdir -p $HOME/.local/share/$NVIM_APPNAME/site

  clean:state:
    desc: delete the downloaded plugins
    cmds:
      - rm -rf $HOME/.local/state/$NVIM_APPNAME
      - mkdir -p $HOME/.local/state/$NVIM_APPNAME/swap
      - mkdir -p $HOME/.local/state/$NVIM_APPNAME/undo
